[package]
name = "vsql-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "VelocitySQL console: embedded REPL and management tool"

[[bin]]
name = "velocitysql-cli"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }

vsql-catalog = { workspace = true }
vsql-executor = { workspace = true }
vsql-types = { workspace = true }

[lints]
workspace = true
